// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: pluginframework/v1/stream.proto

package pluginframeworkv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PluginStreamMessage is the base message for bidirectional plugin stream communication.
// It uses oneof to support different message types in the plugin communication protocol.
type PluginStreamMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*PluginStreamMessage_Register
	//	*PluginStreamMessage_RpcCall
	//	*PluginStreamMessage_RpcResponse
	//	*PluginStreamMessage_Error
	Payload       isPluginStreamMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginStreamMessage) Reset() {
	*x = PluginStreamMessage{}
	mi := &file_pluginframework_v1_stream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginStreamMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginStreamMessage) ProtoMessage() {}

func (x *PluginStreamMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pluginframework_v1_stream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginStreamMessage.ProtoReflect.Descriptor instead.
func (*PluginStreamMessage) Descriptor() ([]byte, []int) {
	return file_pluginframework_v1_stream_proto_rawDescGZIP(), []int{0}
}

func (x *PluginStreamMessage) GetPayload() isPluginStreamMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PluginStreamMessage) GetRegister() *PluginRegister {
	if x != nil {
		if x, ok := x.Payload.(*PluginStreamMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *PluginStreamMessage) GetRpcCall() *PluginRPCCall {
	if x != nil {
		if x, ok := x.Payload.(*PluginStreamMessage_RpcCall); ok {
			return x.RpcCall
		}
	}
	return nil
}

func (x *PluginStreamMessage) GetRpcResponse() *PluginRPCResponse {
	if x != nil {
		if x, ok := x.Payload.(*PluginStreamMessage_RpcResponse); ok {
			return x.RpcResponse
		}
	}
	return nil
}

func (x *PluginStreamMessage) GetError() *PluginError {
	if x != nil {
		if x, ok := x.Payload.(*PluginStreamMessage_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isPluginStreamMessage_Payload interface {
	isPluginStreamMessage_Payload()
}

type PluginStreamMessage_Register struct {
	Register *PluginRegister `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type PluginStreamMessage_RpcCall struct {
	RpcCall *PluginRPCCall `protobuf:"bytes,2,opt,name=rpc_call,json=rpcCall,proto3,oneof"`
}

type PluginStreamMessage_RpcResponse struct {
	RpcResponse *PluginRPCResponse `protobuf:"bytes,3,opt,name=rpc_response,json=rpcResponse,proto3,oneof"`
}

type PluginStreamMessage_Error struct {
	Error *PluginError `protobuf:"bytes,4,opt,name=error,proto3,oneof"`
}

func (*PluginStreamMessage_Register) isPluginStreamMessage_Payload() {}

func (*PluginStreamMessage_RpcCall) isPluginStreamMessage_Payload() {}

func (*PluginStreamMessage_RpcResponse) isPluginStreamMessage_Payload() {}

func (*PluginStreamMessage_Error) isPluginStreamMessage_Payload() {}

// PluginRegister is sent by the plugin when it connects to register itself.
type PluginRegister struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginRegister) Reset() {
	*x = PluginRegister{}
	mi := &file_pluginframework_v1_stream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginRegister) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginRegister) ProtoMessage() {}

func (x *PluginRegister) ProtoReflect() protoreflect.Message {
	mi := &file_pluginframework_v1_stream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginRegister.ProtoReflect.Descriptor instead.
func (*PluginRegister) Descriptor() ([]byte, []int) {
	return file_pluginframework_v1_stream_proto_rawDescGZIP(), []int{1}
}

func (x *PluginRegister) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginRegister) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// PluginRPCCall represents an RPC method call to be forwarded to the plugin.
type PluginRPCCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // Unique ID to correlate with response
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`                        // Method name (e.g., "RenewToken", "GetTokenValidity")
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`                      // Encoded request message (protocol-specific)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginRPCCall) Reset() {
	*x = PluginRPCCall{}
	mi := &file_pluginframework_v1_stream_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginRPCCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginRPCCall) ProtoMessage() {}

func (x *PluginRPCCall) ProtoReflect() protoreflect.Message {
	mi := &file_pluginframework_v1_stream_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginRPCCall.ProtoReflect.Descriptor instead.
func (*PluginRPCCall) Descriptor() ([]byte, []int) {
	return file_pluginframework_v1_stream_proto_rawDescGZIP(), []int{2}
}

func (x *PluginRPCCall) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *PluginRPCCall) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *PluginRPCCall) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// PluginRPCResponse is the response from the plugin to an RPC call.
type PluginRPCResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // Correlates with the original RPC call
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`                      // Encoded response message (protocol-specific)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginRPCResponse) Reset() {
	*x = PluginRPCResponse{}
	mi := &file_pluginframework_v1_stream_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginRPCResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginRPCResponse) ProtoMessage() {}

func (x *PluginRPCResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pluginframework_v1_stream_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginRPCResponse.ProtoReflect.Descriptor instead.
func (*PluginRPCResponse) Descriptor() ([]byte, []int) {
	return file_pluginframework_v1_stream_proto_rawDescGZIP(), []int{3}
}

func (x *PluginRPCResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *PluginRPCResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// PluginError represents an error in plugin communication.
type PluginError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginError) Reset() {
	*x = PluginError{}
	mi := &file_pluginframework_v1_stream_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginError) ProtoMessage() {}

func (x *PluginError) ProtoReflect() protoreflect.Message {
	mi := &file_pluginframework_v1_stream_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginError.ProtoReflect.Descriptor instead.
func (*PluginError) Descriptor() ([]byte, []int) {
	return file_pluginframework_v1_stream_proto_rawDescGZIP(), []int{4}
}

func (x *PluginError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PluginError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

var File_pluginframework_v1_stream_proto protoreflect.FileDescriptor

const file_pluginframework_v1_stream_proto_rawDesc = "" +
	"\n" +
	"\x1fpluginframework/v1/stream.proto\x12\x12pluginframework.v1\"\xa7\x02\n" +
	"\x13PluginStreamMessage\x12@\n" +
	"\bregister\x18\x01 \x01(\v2\".pluginframework.v1.PluginRegisterH\x00R\bregister\x12>\n" +
	"\brpc_call\x18\x02 \x01(\v2!.pluginframework.v1.PluginRPCCallH\x00R\arpcCall\x12J\n" +
	"\frpc_response\x18\x03 \x01(\v2%.pluginframework.v1.PluginRPCResponseH\x00R\vrpcResponse\x127\n" +
	"\x05error\x18\x04 \x01(\v2\x1f.pluginframework.v1.PluginErrorH\x00R\x05errorB\t\n" +
	"\apayload\">\n" +
	"\x0ePluginRegister\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"`\n" +
	"\rPluginRPCCall\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"L\n" +
	"\x11PluginRPCResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\";\n" +
	"\vPluginError\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04codeB\xe1\x01\n" +
	"\x16com.pluginframework.v1B\vStreamProtoP\x01ZQgithub.com/guilhem/operator-plugin-framework/pluginframework/v1;pluginframeworkv1\xa2\x02\x03PXX\xaa\x02\x12Pluginframework.V1\xca\x02\x12Pluginframework\\V1\xe2\x02\x1ePluginframework\\V1\\GPBMetadata\xea\x02\x13Pluginframework::V1b\x06proto3"

var (
	file_pluginframework_v1_stream_proto_rawDescOnce sync.Once
	file_pluginframework_v1_stream_proto_rawDescData []byte
)

func file_pluginframework_v1_stream_proto_rawDescGZIP() []byte {
	file_pluginframework_v1_stream_proto_rawDescOnce.Do(func() {
		file_pluginframework_v1_stream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pluginframework_v1_stream_proto_rawDesc), len(file_pluginframework_v1_stream_proto_rawDesc)))
	})
	return file_pluginframework_v1_stream_proto_rawDescData
}

var file_pluginframework_v1_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pluginframework_v1_stream_proto_goTypes = []any{
	(*PluginStreamMessage)(nil), // 0: pluginframework.v1.PluginStreamMessage
	(*PluginRegister)(nil),      // 1: pluginframework.v1.PluginRegister
	(*PluginRPCCall)(nil),       // 2: pluginframework.v1.PluginRPCCall
	(*PluginRPCResponse)(nil),   // 3: pluginframework.v1.PluginRPCResponse
	(*PluginError)(nil),         // 4: pluginframework.v1.PluginError
}
var file_pluginframework_v1_stream_proto_depIdxs = []int32{
	1, // 0: pluginframework.v1.PluginStreamMessage.register:type_name -> pluginframework.v1.PluginRegister
	2, // 1: pluginframework.v1.PluginStreamMessage.rpc_call:type_name -> pluginframework.v1.PluginRPCCall
	3, // 2: pluginframework.v1.PluginStreamMessage.rpc_response:type_name -> pluginframework.v1.PluginRPCResponse
	4, // 3: pluginframework.v1.PluginStreamMessage.error:type_name -> pluginframework.v1.PluginError
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pluginframework_v1_stream_proto_init() }
func file_pluginframework_v1_stream_proto_init() {
	if File_pluginframework_v1_stream_proto != nil {
		return
	}
	file_pluginframework_v1_stream_proto_msgTypes[0].OneofWrappers = []any{
		(*PluginStreamMessage_Register)(nil),
		(*PluginStreamMessage_RpcCall)(nil),
		(*PluginStreamMessage_RpcResponse)(nil),
		(*PluginStreamMessage_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pluginframework_v1_stream_proto_rawDesc), len(file_pluginframework_v1_stream_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pluginframework_v1_stream_proto_goTypes,
		DependencyIndexes: file_pluginframework_v1_stream_proto_depIdxs,
		MessageInfos:      file_pluginframework_v1_stream_proto_msgTypes,
	}.Build()
	File_pluginframework_v1_stream_proto = out.File
	file_pluginframework_v1_stream_proto_goTypes = nil
	file_pluginframework_v1_stream_proto_depIdxs = nil
}
