// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: pluginframework/v1/stream.proto

package pluginframeworkv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PluginFrameworkService_PluginStream_FullMethodName = "/pluginframework.v1.PluginFrameworkService/PluginStream"
)

// PluginFrameworkServiceClient is the client API for PluginFrameworkService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PluginFrameworkService defines the service for plugin stream communication.
type PluginFrameworkServiceClient interface {
	// PluginStream establishes a bidirectional stream for plugin registration and RPC forwarding.
	PluginStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PluginStreamMessage, PluginStreamMessage], error)
}

type pluginFrameworkServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginFrameworkServiceClient(cc grpc.ClientConnInterface) PluginFrameworkServiceClient {
	return &pluginFrameworkServiceClient{cc}
}

func (c *pluginFrameworkServiceClient) PluginStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PluginStreamMessage, PluginStreamMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PluginFrameworkService_ServiceDesc.Streams[0], PluginFrameworkService_PluginStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PluginStreamMessage, PluginStreamMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PluginFrameworkService_PluginStreamClient = grpc.BidiStreamingClient[PluginStreamMessage, PluginStreamMessage]

// PluginFrameworkServiceServer is the server API for PluginFrameworkService service.
// All implementations must embed UnimplementedPluginFrameworkServiceServer
// for forward compatibility.
//
// PluginFrameworkService defines the service for plugin stream communication.
type PluginFrameworkServiceServer interface {
	// PluginStream establishes a bidirectional stream for plugin registration and RPC forwarding.
	PluginStream(grpc.BidiStreamingServer[PluginStreamMessage, PluginStreamMessage]) error
	mustEmbedUnimplementedPluginFrameworkServiceServer()
}

// UnimplementedPluginFrameworkServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPluginFrameworkServiceServer struct{}

func (UnimplementedPluginFrameworkServiceServer) PluginStream(grpc.BidiStreamingServer[PluginStreamMessage, PluginStreamMessage]) error {
	return status.Errorf(codes.Unimplemented, "method PluginStream not implemented")
}
func (UnimplementedPluginFrameworkServiceServer) mustEmbedUnimplementedPluginFrameworkServiceServer() {
}
func (UnimplementedPluginFrameworkServiceServer) testEmbeddedByValue() {}

// UnsafePluginFrameworkServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginFrameworkServiceServer will
// result in compilation errors.
type UnsafePluginFrameworkServiceServer interface {
	mustEmbedUnimplementedPluginFrameworkServiceServer()
}

func RegisterPluginFrameworkServiceServer(s grpc.ServiceRegistrar, srv PluginFrameworkServiceServer) {
	// If the following call pancis, it indicates UnimplementedPluginFrameworkServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PluginFrameworkService_ServiceDesc, srv)
}

func _PluginFrameworkService_PluginStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PluginFrameworkServiceServer).PluginStream(&grpc.GenericServerStream[PluginStreamMessage, PluginStreamMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PluginFrameworkService_PluginStreamServer = grpc.BidiStreamingServer[PluginStreamMessage, PluginStreamMessage]

// PluginFrameworkService_ServiceDesc is the grpc.ServiceDesc for PluginFrameworkService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PluginFrameworkService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pluginframework.v1.PluginFrameworkService",
	HandlerType: (*PluginFrameworkServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PluginStream",
			Handler:       _PluginFrameworkService_PluginStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pluginframework/v1/stream.proto",
}
